apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: word
  labels:
    app.kubernetes.io/name: word-kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    listeners:
      external:
        type: nodeport
        tls: false
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
      num.partitions: 5
      log.retention.hours: 1
      log.retention.bytes: 2500000
      log.segment.bytes: 500000
      compression.type: "snappy"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

